/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* Tue Nov 19 00:02:15 2013 */

/* parameterized module instance */
adc_pll __ (.CLK( ), .CLKOP( ), .LOCK( ));
