/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* Tue Nov 19 14:44:48 2013 */

/* parameterized module instance */
ddr_generic __ (.clk( ), .sclk( ), .datain( ), .q( ));
