/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* Wed Nov 06 20:36:49 2013 */

/* parameterized module instance */
my_pll __ (.CLK( ), .CLKOP( ), .CLKOK( ), .LOCK( ));
