/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* Mon Dec 02 17:32:05 2013 */

/* parameterized module instance */
adc_clock __ (.CLK( ), .CLKOP( ), .LOCK( ));
