/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 6.2 */
/* C:\lscc\diamond\2.2_x64\ispfpga\bin\nt64\scuba.exe -w -n adc_ram -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type bram -wp 10 -rp 0011 -rdata_width 64 -data_width 64 -num_rows 2048 -outdata REGISTERED -cascade -1 -e  */
/* Wed Nov 20 19:44:24 2013 */


`timescale 1 ns / 1 ps
module adc_ram (WrAddress, RdAddress, Data, WE, RdClock, RdClockEn, 
    Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [10:0] WrAddress;
    input wire [10:0] RdAddress;
    input wire [63:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [63:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam adc_ram_0_0_7.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_0_7.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_0_7.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_0_7.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_0_7.GSR = "DISABLED" ;
    defparam adc_ram_0_0_7.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_0_7.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_0_7.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_0_7.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_0_7 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[0]), .DOB1(Q[1]), .DOB2(Q[2]), 
        .DOB3(Q[3]), .DOB4(Q[4]), .DOB5(Q[5]), .DOB6(Q[6]), .DOB7(Q[7]), 
        .DOB8(Q[8]), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam adc_ram_0_1_6.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_1_6.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_1_6.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_1_6.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_1_6.GSR = "DISABLED" ;
    defparam adc_ram_0_1_6.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_1_6.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_1_6.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_1_6.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_1_6 (.DIA0(Data[9]), .DIA1(Data[10]), .DIA2(Data[11]), 
        .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), .DIA6(Data[15]), 
        .DIA7(Data[16]), .DIA8(Data[17]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[9]), .DOB1(Q[10]), .DOB2(Q[11]), 
        .DOB3(Q[12]), .DOB4(Q[13]), .DOB5(Q[14]), .DOB6(Q[15]), .DOB7(Q[16]), 
        .DOB8(Q[17]), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam adc_ram_0_2_5.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_2_5.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_2_5.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_2_5.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_2_5.GSR = "DISABLED" ;
    defparam adc_ram_0_2_5.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_2_5.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_2_5.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_2_5.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_2_5 (.DIA0(Data[18]), .DIA1(Data[19]), .DIA2(Data[20]), 
        .DIA3(Data[21]), .DIA4(Data[22]), .DIA5(Data[23]), .DIA6(Data[24]), 
        .DIA7(Data[25]), .DIA8(Data[26]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[18]), .DOB1(Q[19]), .DOB2(Q[20]), 
        .DOB3(Q[21]), .DOB4(Q[22]), .DOB5(Q[23]), .DOB6(Q[24]), .DOB7(Q[25]), 
        .DOB8(Q[26]), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam adc_ram_0_3_4.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_3_4.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_3_4.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_3_4.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_3_4.GSR = "DISABLED" ;
    defparam adc_ram_0_3_4.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_3_4.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_3_4.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_3_4.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_3_4 (.DIA0(Data[27]), .DIA1(Data[28]), .DIA2(Data[29]), 
        .DIA3(Data[30]), .DIA4(Data[31]), .DIA5(Data[32]), .DIA6(Data[33]), 
        .DIA7(Data[34]), .DIA8(Data[35]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[27]), .DOB1(Q[28]), .DOB2(Q[29]), 
        .DOB3(Q[30]), .DOB4(Q[31]), .DOB5(Q[32]), .DOB6(Q[33]), .DOB7(Q[34]), 
        .DOB8(Q[35]), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam adc_ram_0_4_3.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_4_3.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_4_3.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_4_3.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_4_3.GSR = "DISABLED" ;
    defparam adc_ram_0_4_3.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_4_3.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_4_3.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_4_3.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_4_3 (.DIA0(Data[36]), .DIA1(Data[37]), .DIA2(Data[38]), 
        .DIA3(Data[39]), .DIA4(Data[40]), .DIA5(Data[41]), .DIA6(Data[42]), 
        .DIA7(Data[43]), .DIA8(Data[44]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[36]), .DOB1(Q[37]), .DOB2(Q[38]), 
        .DOB3(Q[39]), .DOB4(Q[40]), .DOB5(Q[41]), .DOB6(Q[42]), .DOB7(Q[43]), 
        .DOB8(Q[44]), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam adc_ram_0_5_2.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_5_2.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_5_2.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_5_2.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_5_2.GSR = "DISABLED" ;
    defparam adc_ram_0_5_2.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_5_2.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_5_2.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_5_2.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_5_2 (.DIA0(Data[45]), .DIA1(Data[46]), .DIA2(Data[47]), 
        .DIA3(Data[48]), .DIA4(Data[49]), .DIA5(Data[50]), .DIA6(Data[51]), 
        .DIA7(Data[52]), .DIA8(Data[53]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[45]), .DOB1(Q[46]), .DOB2(Q[47]), 
        .DOB3(Q[48]), .DOB4(Q[49]), .DOB5(Q[50]), .DOB6(Q[51]), .DOB7(Q[52]), 
        .DOB8(Q[53]), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam adc_ram_0_6_1.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_6_1.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_6_1.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_6_1.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_6_1.GSR = "DISABLED" ;
    defparam adc_ram_0_6_1.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_6_1.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_6_1.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_6_1.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_6_1 (.DIA0(Data[54]), .DIA1(Data[55]), .DIA2(Data[56]), 
        .DIA3(Data[57]), .DIA4(Data[58]), .DIA5(Data[59]), .DIA6(Data[60]), 
        .DIA7(Data[61]), .DIA8(Data[62]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[54]), .DOB1(Q[55]), .DOB2(Q[56]), 
        .DOB3(Q[57]), .DOB4(Q[58]), .DOB5(Q[59]), .DOB6(Q[60]), .DOB7(Q[61]), 
        .DOB8(Q[62]), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam adc_ram_0_7_0.CSDECODE_B = "0b000" ;
    defparam adc_ram_0_7_0.CSDECODE_A = "0b000" ;
    defparam adc_ram_0_7_0.WRITEMODE_B = "NORMAL" ;
    defparam adc_ram_0_7_0.WRITEMODE_A = "NORMAL" ;
    defparam adc_ram_0_7_0.GSR = "DISABLED" ;
    defparam adc_ram_0_7_0.REGMODE_B = "OUTREG" ;
    defparam adc_ram_0_7_0.REGMODE_A = "OUTREG" ;
    defparam adc_ram_0_7_0.DATA_WIDTH_B = 9 ;
    defparam adc_ram_0_7_0.DATA_WIDTH_A = 9 ;
    DP16KC adc_ram_0_7_0 (.DIA0(Data[63]), .DIA1(scuba_vlo), .DIA2(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(WrAddress[8]), 
        .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), .CEA(WrClockEn), .CLKA(WrClock), 
        .OCEA(WrClockEn), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), 
        .ADB4(RdAddress[1]), .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), 
        .ADB8(RdAddress[5]), .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), 
        .ADB11(RdAddress[8]), .ADB12(RdAddress[9]), .ADB13(RdAddress[10]), 
        .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[63]), .DOB1(), .DOB2(), .DOB3(), 
        .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="adc_ram.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;



    // exemplar begin
    // exemplar attribute adc_ram_0_0_7 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_0_7 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_0_7 RESETMODE SYNC
    // exemplar attribute adc_ram_0_1_6 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_1_6 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_1_6 RESETMODE SYNC
    // exemplar attribute adc_ram_0_2_5 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_2_5 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_2_5 RESETMODE SYNC
    // exemplar attribute adc_ram_0_3_4 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_3_4 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_3_4 RESETMODE SYNC
    // exemplar attribute adc_ram_0_4_3 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_4_3 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_4_3 RESETMODE SYNC
    // exemplar attribute adc_ram_0_5_2 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_5_2 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_5_2 RESETMODE SYNC
    // exemplar attribute adc_ram_0_6_1 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_6_1 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_6_1 RESETMODE SYNC
    // exemplar attribute adc_ram_0_7_0 MEM_LPC_FILE adc_ram.lpc
    // exemplar attribute adc_ram_0_7_0 MEM_INIT_FILE 
    // exemplar attribute adc_ram_0_7_0 RESETMODE SYNC
    // exemplar end

endmodule
