/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* C:\lscc\diamond\2.2_x64\ispfpga\bin\nt64\scuba.exe -w -n ddr_generic -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type iol -mode in -io_type LVCMOS25 -width 8 -freq_in 125 -gear 1 -clk pll -aligned -e  */
/* Fri Nov 29 17:19:42 2013 */


`timescale 1 ns / 1 ps
module ddr_generic (clk, pll_lock, pll_reset, sclk, datain, q)/* synthesis syn_noprune=1 *//* synthesis NGD_DRC_MASK=1 */;// exemplar attribute ddr_generic dont_touch true 
    input wire clk;
    input wire pll_reset;
    input wire [7:0] datain;
    output wire pll_lock;
    output wire sclk;
    output wire [15:0] q;

    wire qb7;
    wire qa7;
    wire qb6;
    wire qa6;
    wire qb5;
    wire qa5;
    wire qb4;
    wire qa4;
    wire qb3;
    wire qa3;
    wire qb2;
    wire qa2;
    wire qb1;
    wire qa1;
    wire qb0;
    wire qa0;
    wire clkok2;
    wire clkok;
    wire sclk_t;
    wire clkop;
    wire scuba_vlo;
    wire clkintfb;
    wire dataini_t7;
    wire dataini_t6;
    wire dataini_t5;
    wire dataini_t4;
    wire dataini_t3;
    wire dataini_t2;
    wire dataini_t1;
    wire dataini_t0;
    wire buf_clk;
    wire buf_dataini7;
    wire buf_dataini6;
    wire buf_dataini5;
    wire buf_dataini4;
    wire buf_dataini3;
    wire buf_dataini2;
    wire buf_dataini1;
    wire buf_dataini0;

    IDDRXD1 Inst_IDDRXD1_0_7 (.D(dataini_t7), .SCLK(sclk_t), .QA(qa7), .QB(qb7))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    IDDRXD1 Inst_IDDRXD1_0_6 (.D(dataini_t6), .SCLK(sclk_t), .QA(qa6), .QB(qb6))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    IDDRXD1 Inst_IDDRXD1_0_5 (.D(dataini_t5), .SCLK(sclk_t), .QA(qa5), .QB(qb5))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    IDDRXD1 Inst_IDDRXD1_0_4 (.D(dataini_t4), .SCLK(sclk_t), .QA(qa4), .QB(qb4))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    IDDRXD1 Inst_IDDRXD1_0_3 (.D(dataini_t3), .SCLK(sclk_t), .QA(qa3), .QB(qb3))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    IDDRXD1 Inst_IDDRXD1_0_2 (.D(dataini_t2), .SCLK(sclk_t), .QA(qa2), .QB(qb2))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    IDDRXD1 Inst_IDDRXD1_0_1 (.D(dataini_t1), .SCLK(sclk_t), .QA(qa1), .QB(qb1))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    IDDRXD1 Inst_IDDRXD1_0_0 (.D(dataini_t0), .SCLK(sclk_t), .QA(qa0), .QB(qb0))
             /* synthesis IDDRAPPS="SCLK_PLLALIGNED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam Inst3_EHXPLLF.FEEDBK_PATH = "INTERNAL" ;
    defparam Inst3_EHXPLLF.CLKOK_BYPASS = "DISABLED" ;
    defparam Inst3_EHXPLLF.CLKOS_BYPASS = "DISABLED" ;
    defparam Inst3_EHXPLLF.CLKOP_BYPASS = "DISABLED" ;
    defparam Inst3_EHXPLLF.CLKOK_INPUT = "CLKOS" ;
    defparam Inst3_EHXPLLF.DELAY_PWD = "DISABLED" ;
    defparam Inst3_EHXPLLF.DELAY_VAL = 0 ;
    defparam Inst3_EHXPLLF.CLKOS_TRIM_DELAY = 0 ;
    defparam Inst3_EHXPLLF.CLKOS_TRIM_POL = "RISING" ;
    defparam Inst3_EHXPLLF.CLKOP_TRIM_DELAY = 0 ;
    defparam Inst3_EHXPLLF.CLKOP_TRIM_POL = "RISING" ;
    defparam Inst3_EHXPLLF.PHASE_DELAY_CNTL = "STATIC" ;
    defparam Inst3_EHXPLLF.DUTY = 8 ;
    defparam Inst3_EHXPLLF.PHASEADJ = "90.0" ;
    defparam Inst3_EHXPLLF.CLKOK_DIV = 2 ;
    defparam Inst3_EHXPLLF.CLKOP_DIV = 8 ;
    defparam Inst3_EHXPLLF.CLKFB_DIV = 1 ;
    defparam Inst3_EHXPLLF.CLKI_DIV = 1 ;
    defparam Inst3_EHXPLLF.FIN = "125.000000" ;
    EHXPLLF Inst3_EHXPLLF (.CLKI(buf_clk), .CLKFB(clkintfb), .RST(pll_reset), 
        .RSTK(scuba_vlo), .WRDEL(scuba_vlo), .DRPAI3(scuba_vlo), .DRPAI2(scuba_vlo), 
        .DRPAI1(scuba_vlo), .DRPAI0(scuba_vlo), .DFPAI3(scuba_vlo), .DFPAI2(scuba_vlo), 
        .DFPAI1(scuba_vlo), .DFPAI0(scuba_vlo), .FDA3(scuba_vlo), .FDA2(scuba_vlo), 
        .FDA1(scuba_vlo), .FDA0(scuba_vlo), .CLKOP(clkop), .CLKOS(sclk_t), 
        .CLKOK(clkok), .CLKOK2(clkok2), .LOCK(pll_lock), .CLKINTFB(clkintfb))
             /* synthesis FREQUENCY_PIN_CLKOP="125.000000" */
             /* synthesis FREQUENCY_PIN_CLKOS="125.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="125.000000" */
             /* synthesis FREQUENCY_PIN_CLKOK="62.500000" */;

    DELAYC udel_dataini7 (.A(buf_dataini7), .Z(dataini_t7));

    DELAYC udel_dataini6 (.A(buf_dataini6), .Z(dataini_t6));

    DELAYC udel_dataini5 (.A(buf_dataini5), .Z(dataini_t5));

    DELAYC udel_dataini4 (.A(buf_dataini4), .Z(dataini_t4));

    DELAYC udel_dataini3 (.A(buf_dataini3), .Z(dataini_t3));

    DELAYC udel_dataini2 (.A(buf_dataini2), .Z(dataini_t2));

    DELAYC udel_dataini1 (.A(buf_dataini1), .Z(dataini_t1));

    DELAYC udel_dataini0 (.A(buf_dataini0), .Z(dataini_t0));

    IB Inst2_IB (.I(clk), .O(buf_clk))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB7 (.I(datain[7]), .O(buf_dataini7))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB6 (.I(datain[6]), .O(buf_dataini6))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB5 (.I(datain[5]), .O(buf_dataini5))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB4 (.I(datain[4]), .O(buf_dataini4))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB3 (.I(datain[3]), .O(buf_dataini3))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB2 (.I(datain[2]), .O(buf_dataini2))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB1 (.I(datain[1]), .O(buf_dataini1))
             /* synthesis IO_TYPE="LVCMOS25" */;

    IB Inst1_IB0 (.I(datain[0]), .O(buf_dataini0))
             /* synthesis IO_TYPE="LVCMOS25" */;

    assign sclk = sclk_t;
    assign q[15] = qb7;
    assign q[14] = qb6;
    assign q[13] = qb5;
    assign q[12] = qb4;
    assign q[11] = qb3;
    assign q[10] = qb2;
    assign q[9] = qb1;
    assign q[8] = qb0;
    assign q[7] = qa7;
    assign q[6] = qa6;
    assign q[5] = qa5;
    assign q[4] = qa4;
    assign q[3] = qa3;
    assign q[2] = qa2;
    assign q[1] = qa1;
    assign q[0] = qa0;


    // exemplar begin
    // exemplar attribute Inst_IDDRXD1_0_7 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst_IDDRXD1_0_6 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst_IDDRXD1_0_5 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst_IDDRXD1_0_4 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst_IDDRXD1_0_3 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst_IDDRXD1_0_2 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst_IDDRXD1_0_1 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst_IDDRXD1_0_0 IDDRAPPS SCLK_PLLALIGNED
    // exemplar attribute Inst3_EHXPLLF FREQUENCY_PIN_CLKOP 125.000000
    // exemplar attribute Inst3_EHXPLLF FREQUENCY_PIN_CLKOS 125.000000
    // exemplar attribute Inst3_EHXPLLF FREQUENCY_PIN_CLKI 125.000000
    // exemplar attribute Inst3_EHXPLLF FREQUENCY_PIN_CLKOK 62.500000
    // exemplar attribute Inst2_IB IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB7 IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB6 IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB5 IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB4 IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB3 IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB2 IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB1 IO_TYPE LVCMOS25
    // exemplar attribute Inst1_IB0 IO_TYPE LVCMOS25
    // exemplar end

endmodule
