/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* Mon Dec 02 17:32:13 2013 */

/* parameterized module instance */
ddr_generic __ (.clk( ), .clkdiv_reset( ), .gdll_lock( ), 
    .gdll_resetn( ), .gdll_uddcntl( ), .sclk( ), .datain( ), .q( ));
