/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* Fri Nov 29 17:19:42 2013 */

/* parameterized module instance */
ddr_generic __ (.clk( ), .pll_lock( ), .pll_reset( ), .sclk( ), 
    .datain( ), .q( ));
