/* Verilog module instantiation template generated by SCUBA ispLever_v8.1_PROD_Build (20) */
/* Module Version: 7.1 */
/* Thu Dec 30 11:35:56 2010 */

/* parameterized module instance */
spram_8192_64 __ (.Clock( ), .ClockEn( ), .Reset( ), .ByteEn( ), .WE( ), 
    .Address( ), .Data( ), .Q( ));
