/* Verilog module instantiation template generated by SCUBA Diamond_1.1_Production (517) */
/* Module Version: 5.4 */
/* Fri Apr 15 17:18:48 2011 */

/* parameterized module instance */
fifo_down __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ));
