/* Verilog module instantiation template generated by SCUBA ispLever_v8.1_PROD_Build (20) */
/* Module Version: 5.2 */
/* Tue Dec 21 16:26:07 2010 */

/* parameterized module instance */
pll __ (.CLK( ), .CLKOP( ), .LOCK( ));
