/* Verilog module instantiation template generated by SCUBA ispLever_v8.1_PROD_Build (20) */
/* Module Version: 7.1 */
/* Fri Dec 03 15:42:44 2010 */

/* parameterized module instance */
spram_16384_16 __ (.Clock( ), .ClockEn( ), .Reset( ), .ByteEn( ), .WE( ), 
    .Address( ), .Data( ), .Q( ));
