//=============================================================================
// Verilog module generated by IPExpress    01/20/2010    14:16:54          
// Filename: sgdma_bb.v                                            
// Copyright(c) 2007 Lattice Semiconductor Corporation. All rights reserved.   
//=============================================================================

//------------------------------------------------
// sgdma module Definition            
//------------------------------------------------

module sgdma (
    input clk,
    input rstn,
    input rst_core,
    output a_cyc,
    output a_stb,
    output a_lock,
    output a_we,
    output [2:0] a_cti,
    output [7:0] a_sel,
    output [31:0] a_addr,
    output [63:0] a_wdat,
    input [63:0] a_rdat,
    input a_ack,
    input a_err,
    input a_retry,
    input a_eod,
    output b_cyc,
    output b_stb,
    output b_lock,
    output b_we,
    output [2:0] b_cti,
    output [7:0] b_sel,
    output [31:0] b_addr,
    output [63:0] b_wdat,
    input [63:0] b_rdat,
    input b_ack,
    input b_err,
    input b_retry,
    input b_eod,
    output b_active,
    input [31:0] saddr,
    input [31:0] swdat,
    output [31:0] srdat,
    input scyc,
    input sstb,
    input [3:0] ssel,
    input swe,
    output sack,
    output serr,
    input [1:0] dma_req,
    output [1:0] dma_ack,
    output [1:0] eventx,
    output [1:0] errorx,
    output [0:0] actchan,
    output [0:0] subchan,
    output a_active,
    output [15:0] max_burst_size,
    output [9:0] bd_waddr,
    output [9:0] bd_raddr,
    output [31:0] bd_wdat,
    input [31:0] bd_rdat,
    output bd_we,
    output bd_re,
    input bd_rval
    );

endmodule

