/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_latticesemi_lpa_apps_sfif_SFIF_UI */

#ifndef _Included_com_latticesemi_lpa_apps_sfif_SFIF_UI
#define _Included_com_latticesemi_lpa_apps_sfif_SFIF_UI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_FOCUS_TRAVERSABLE_UNKNOWN
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_FOCUS_TRAVERSABLE_DEFAULT
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_FOCUS_TRAVERSABLE_SET
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_FOCUS_TRAVERSABLE_SET 2L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_TOP_ALIGNMENT
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_TOP_ALIGNMENT 0.0f
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_CENTER_ALIGNMENT
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_CENTER_ALIGNMENT 0.5f
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_BOTTOM_ALIGNMENT
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_BOTTOM_ALIGNMENT 1.0f
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_LEFT_ALIGNMENT
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_LEFT_ALIGNMENT 0.0f
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_RIGHT_ALIGNMENT
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_RIGHT_ALIGNMENT 1.0f
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID -7644114512714619750i64
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID 4613797578919906343i64
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_INCLUDE_SELF
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_INCLUDE_SELF 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_SEARCH_HEAVYWEIGHTS
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_SEARCH_HEAVYWEIGHTS 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_OPENED
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_OPENED 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID 4497834738069338734i64
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_DEFAULT_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_DEFAULT_CURSOR 0L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_CROSSHAIR_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_CROSSHAIR_CURSOR 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_TEXT_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_TEXT_CURSOR 2L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_WAIT_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_WAIT_CURSOR 3L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_SW_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_SW_RESIZE_CURSOR 4L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_SE_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_SE_RESIZE_CURSOR 5L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_NW_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_NW_RESIZE_CURSOR 6L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_NE_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_NE_RESIZE_CURSOR 7L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_N_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_N_RESIZE_CURSOR 8L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_S_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_S_RESIZE_CURSOR 9L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_W_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_W_RESIZE_CURSOR 10L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_E_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_E_RESIZE_CURSOR 11L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_HAND_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_HAND_CURSOR 12L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MOVE_CURSOR
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MOVE_CURSOR 13L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_NORMAL
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_NORMAL 0L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_ICONIFIED
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_ICONIFIED 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MAXIMIZED_HORIZ
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MAXIMIZED_HORIZ 2L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MAXIMIZED_VERT
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MAXIMIZED_VERT 4L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MAXIMIZED_BOTH
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MAXIMIZED_BOTH 6L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_serialVersionUID 2673458971256075116i64
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_EXIT_ON_CLOSE
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_EXIT_ON_CLOSE 3L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_THRUPUT_MODE
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_THRUPUT_MODE 0L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_READ_CYC_MODE
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_READ_CYC_MODE 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_WRITE_CYC_MODE
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_WRITE_CYC_MODE 2L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MRD_TLPS
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MRD_TLPS 1L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MWR_TLPS
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MWR_TLPS 2L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MRD_MWR_TLPS
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MRD_MWR_TLPS 3L
#undef com_latticesemi_lpa_apps_sfif_SFIF_UI_MRD_MWR_CTRL_TLPS
#define com_latticesemi_lpa_apps_sfif_SFIF_UI_MRD_MWR_CTRL_TLPS 4L
/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getVersionStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getVersionStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getDrvrResourceStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getDrvrResourceStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getPCIResourceStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getPCIResourceStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getCfgRegsStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getCfgRegsStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getCapRegStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getCapRegStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getExtraInfoStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getExtraInfoStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getPCSysBufStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getPCSysBufStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_clrPCSysBuf
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1clrPCSysBuf
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getSFIFRxFIFOStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getSFIFRxFIFOStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_setupSFIF
 * Signature: (IIIIIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1setupSFIF
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_getSFIFRegsArray
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1getSFIFRegsArray
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_startSFIF
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1startSFIF
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_stopSFIF
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1stopSFIF
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_sfif_SFIF_UI
 * Method:    CPP_testGPIOAccess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_latticesemi_lpa_apps_sfif_SFIF_1UI_CPP_1testGPIOAccess
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
