#==============================================================================
# Makefile to build an executable from a single, same named, source file.
# This makefile would be used to build tests, applications, etc. where a
# single C file, test.c, having main(), possibly calls functions in other
# pre-compiled object files.
#
# The build tools, flags, include paths, etc. are taken from the platform's
# rules.make file, so PLATFORM_DIR must be set to point to the root platform
# software directory.
#
# Customization for a specific build platform is done through the inclusion
# of rules.make from the Platform directory and sysDefs.h
#
# NOTE! The JAVA_INCS variable must point to the location of the Java JDK
# installed on the system.  The default value is Java in Fedora Core5
#===============================================================================



# Make this the platform directory for testing
include $(LSC_PCIEAPI_DIR)/rules.make

.SUFFIXES: .o .c



JAVA_INCS = -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux

CXXFLAGS:= $(CXXFLAGS) $(JAVA_INCS)


#----------------------------------------------------
# build the shared library
#----------------------------------------------------

dll: libCpp_Jni.so

libCpp_Jni.so :  dllmain.o Cpp_Jni.o
	g++ -o libCpp_Jni.so -shared -Wl,-soname,libCpp_Jni.so $(JAVA_INCS) $(CXXEXEFLAGS) dllmain.o Cpp_Jni.o  -lc -lrt -L$(LSC_PCIEAPI_DIR) -llscpcieapi



#------------------------------------------------------------------------
# Clean-up all .o files in the directory
#------------------------------------------------------------------------
clean :
	-rm *.o
	-rm *.so


