/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_latticesemi_lpa_apps_pcie_DemoUI */

#ifndef _Included_com_latticesemi_lpa_apps_pcie_DemoUI
#define _Included_com_latticesemi_lpa_apps_pcie_DemoUI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_latticesemi_lpa_apps_pcie_DemoUI_FOCUS_TRAVERSABLE_UNKNOWN
#define com_latticesemi_lpa_apps_pcie_DemoUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_FOCUS_TRAVERSABLE_DEFAULT
#define com_latticesemi_lpa_apps_pcie_DemoUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_FOCUS_TRAVERSABLE_SET
#define com_latticesemi_lpa_apps_pcie_DemoUI_FOCUS_TRAVERSABLE_SET 2L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_TOP_ALIGNMENT
#define com_latticesemi_lpa_apps_pcie_DemoUI_TOP_ALIGNMENT 0.0f
#undef com_latticesemi_lpa_apps_pcie_DemoUI_CENTER_ALIGNMENT
#define com_latticesemi_lpa_apps_pcie_DemoUI_CENTER_ALIGNMENT 0.5f
#undef com_latticesemi_lpa_apps_pcie_DemoUI_BOTTOM_ALIGNMENT
#define com_latticesemi_lpa_apps_pcie_DemoUI_BOTTOM_ALIGNMENT 1.0f
#undef com_latticesemi_lpa_apps_pcie_DemoUI_LEFT_ALIGNMENT
#define com_latticesemi_lpa_apps_pcie_DemoUI_LEFT_ALIGNMENT 0.0f
#undef com_latticesemi_lpa_apps_pcie_DemoUI_RIGHT_ALIGNMENT
#define com_latticesemi_lpa_apps_pcie_DemoUI_RIGHT_ALIGNMENT 1.0f
#undef com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID
#define com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID -7644114512714619750i64
#undef com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID
#define com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID 4613797578919906343i64
#undef com_latticesemi_lpa_apps_pcie_DemoUI_INCLUDE_SELF
#define com_latticesemi_lpa_apps_pcie_DemoUI_INCLUDE_SELF 1L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_SEARCH_HEAVYWEIGHTS
#define com_latticesemi_lpa_apps_pcie_DemoUI_SEARCH_HEAVYWEIGHTS 1L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_OPENED
#define com_latticesemi_lpa_apps_pcie_DemoUI_OPENED 1L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID
#define com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID 4497834738069338734i64
#undef com_latticesemi_lpa_apps_pcie_DemoUI_DEFAULT_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_DEFAULT_CURSOR 0L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_CROSSHAIR_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_CROSSHAIR_CURSOR 1L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_TEXT_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_TEXT_CURSOR 2L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_WAIT_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_WAIT_CURSOR 3L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_SW_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_SW_RESIZE_CURSOR 4L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_SE_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_SE_RESIZE_CURSOR 5L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_NW_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_NW_RESIZE_CURSOR 6L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_NE_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_NE_RESIZE_CURSOR 7L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_N_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_N_RESIZE_CURSOR 8L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_S_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_S_RESIZE_CURSOR 9L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_W_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_W_RESIZE_CURSOR 10L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_E_RESIZE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_E_RESIZE_CURSOR 11L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_HAND_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_HAND_CURSOR 12L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_MOVE_CURSOR
#define com_latticesemi_lpa_apps_pcie_DemoUI_MOVE_CURSOR 13L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_NORMAL
#define com_latticesemi_lpa_apps_pcie_DemoUI_NORMAL 0L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_ICONIFIED
#define com_latticesemi_lpa_apps_pcie_DemoUI_ICONIFIED 1L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_MAXIMIZED_HORIZ
#define com_latticesemi_lpa_apps_pcie_DemoUI_MAXIMIZED_HORIZ 2L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_MAXIMIZED_VERT
#define com_latticesemi_lpa_apps_pcie_DemoUI_MAXIMIZED_VERT 4L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_MAXIMIZED_BOTH
#define com_latticesemi_lpa_apps_pcie_DemoUI_MAXIMIZED_BOTH 6L
#undef com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID
#define com_latticesemi_lpa_apps_pcie_DemoUI_serialVersionUID 2673458971256075116i64
#undef com_latticesemi_lpa_apps_pcie_DemoUI_EXIT_ON_CLOSE
#define com_latticesemi_lpa_apps_pcie_DemoUI_EXIT_ON_CLOSE 3L
/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getVersionStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getVersionStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getDrvrResourceStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getDrvrResourceStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getPCIResourceStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getPCIResourceStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getCfgRegsStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getCfgRegsStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getCapRegStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getCapRegStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getExtCapRegsStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getExtCapRegsStr
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_runEBRTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1runEBRTest
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_readEBRMem
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1readEBRMem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_writeEBRMem
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1writeEBRMem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_clearEBRMem
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1clearEBRMem
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_fillEBRMem
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1fillEBRMem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_loadEBRFromFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1loadEBRFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_saveEBRToFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1saveEBRToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_readBAR0Mem
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1readBAR0Mem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_writeBAR0Mem
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1writeBAR0Mem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_readBAR1Mem
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1readBAR1Mem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_writeBAR1Mem
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1writeBAR1Mem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_runLEDTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1runLEDTest
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_setLED
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1setLED
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_runLED16SegTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1runLED16SegTest
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_setLED16Seg
 * Signature: (C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1setLED16Seg__C
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_setLED16Seg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1setLED16Seg__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getLED16Seg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getLED16Seg
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getDIPsw
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getDIPsw
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_runCounter
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1runCounter
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_getCounter
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1getCounter
  (JNIEnv *, jobject);

/*
 * Class:     com_latticesemi_lpa_apps_pcie_DemoUI
 * Method:    CPP_setReloadCount
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_latticesemi_lpa_apps_pcie_DemoUI_CPP_1setReloadCount
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
